<?php
/*
MIT License

Copyright (c) 2021 Anweshan Roy Chowdhury

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 */
namespace Anweshan\Image\Manipulators;

use Intervention\Image\Image;

/**
 * The class Flip, manipulates the image by getting flip-flop of the original.
 * 
 *By definition, a **flipped image** or **reversed image**, the more formal term, is a static or moving image that is generated by a mirror-reversal of an original across a horizontal axis (by property value `h`) and a **flopped image** is mirrored across the vertical axis (by property value `v`). A flip-flop image, is generated when the orginal is mirrored both along the horizontal and vertical axis.
 * 
 * 
 * @property string $flip The flip property, accepts `v`, `h` and `both`.
 * 
 * @package Anweshan\Image
 * @subpackage Manipulators
 * 
 * @author Anweshan
 * @since 2021
 * @version 2
 * @license MIT
 *        
 */
class Flip extends BaseManipulator {

	/**
	 * Perform flip image manipulation.
	 * {@inheritdoc}
	 * @see \Anweshan\Image\Manipulators\BaseManipulator::run()
	 */
	public function run(Image $image) : Image{
		if($flip = $this->getFlip()){
			if($flip === 'both'){
				$flip = 'h';
				$image = $image->flip('v');
			}
			$image = $image->flip($flip);
		}
		return $image;
	}
	
	/**
	 * Resolve flip.
	 * @return string|null The resolved flip.
	 */
	public function getFlip()
	{
		if (in_array($this->flip, ['h', 'v', 'both'], true)) {
			return $this->flip;
		}
		return;
	}
	
	/**
	 * Returns the property flip.
	 * {@inheritDoc}
	 */
	public function __toString() : string {
		return parent::getProperties('flip');
	}
}

